### ISSUE TITLE
GitHub actions triggering twice

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/litdata#220]
Probably a configuration issue. The CI triggers all jobs twice on a PR:

<img width="851" alt="image" src="https://github.com/Lightning-AI/litdata/assets/5495193/9997a647-9903-466b-aa08-a7fb1bdea0d5">

Example: https://github.com/Lightning-AI/litdata/pull/217

**Comment by deependujha** [comment]
But, one is for `pull_request` and the other is for `push`.

I guess, When your PR checks were running, the PR was merged and triggered a push CI action too.

**Comment by deependujha** [comment]
Sorry, I just observed this behavior. For a small nitpick fix, I coded on github and opened a PR.

In this case, it did run `pull_request` and `push` CI.

![Screenshot from 2024-07-12 16-59-54](https://github.com/user-attachments/assets/df8e371e-a567-4f54-9454-2ac3712cd1c7)

**Comment by deependujha** [comment]
```yaml
# .github/workflows/ci-testing.yml

name: CI testing

on: # Trigger the workflow on push or pull request, but only for the main branch
  push: {}
  pull_request:
    branches: [main]
```

push runs on all branches. So, when we code on litdata github repo and make a pr, a push CI runs and since making a PR for main pull_request CI runs.

The fix is:
```yaml
# .github/workflows/ci-testing.yml

name: CI testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

```
